language: python

python:
  - '2.6'
  - '2.7'

install:
  - 'pip install -e .[dev]'

script:
  - 'python manage.py test'

notifications:
  irc:
    channels:
      - "irc.freenode.org#richard"
    on_success: change
    on_failure: always
